在 NumPy 中，所有赋值运算并不会为数组及其元素创建副本。

要创建数组的副本，需要使用 `numpy.ndarray.copy()` 方法。

In [5]:
import numpy as np
a = np.arange(1, 10).reshape([3, 3])
print(a)
b = a
b[::1] = 0
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
a = np.arange(1, 10).reshape([3, 3])
print(a)
b = a.copy()
b[::1] = 0
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 索引 ##

数组索引机制指的是用方括号（[]）加序号的形式引用单个数组元素，它的用处很多，比如抽取元素，选取数组的几个元素，甚至为其赋一个新值。

In [8]:
a = np.arange(1, 10)
print(a)
print(a[1])
a = a.reshape([3, 3])
print(a)
print(a[1])
print(a[1,1])
print(a[1][1])

[1 2 3 4 5 6 7 8 9]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
5
5


**切片索引**

切片索引可以用来选取数组的一部分形成新的数组。对于 NumPy 来说，切片索引选取的是原数组的视图，即没有复制数组。

其格式为 `[start:stop:step]`，其中成分均可忽略。另外，对于多维数组，可以对其每一维度进行切片。

In [10]:
a = np.arange(1, 26).reshape([5, 5])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [11]:
print(a[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
print(a[:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
print(a[::2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [14]:
print(a[2:])

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
print(a[::-1])

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [17]:
print(a[:2, :2])

[[1 2]
 [6 7]]


In [18]:
print(a[:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


**dots 索引**

NumPy 允许使用`...`表示足够多的冒号来构建完整的索引列表。

比如，如果 `x` 是 5 维数组：

- `x[1,2,...]` 等于 `x[1,2,:,:,:]`
- `x[...,3]` 等于 `x[:,:,:,:,3]` 
- `x[4,...,5,:]` 等于 `x[4,:,:,5,:]`

In [22]:
a = np.arange(1, 13).reshape([2, 2, 3])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
print(a[1, ...])

[[ 7  8  9]
 [10 11 12]]


In [24]:
print(a[..., 0])

[[ 1  4]
 [ 7 10]]


**整数数组索引**

传入一个数组作为索引，可以选取对应元素

In [25]:
a = np.arange(1, 26).reshape([5, 5])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
print(a[[1, 2, 4]])

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [28]:
print(a[[1, 2, -2]])

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
print(a[[0, 1, 2], [1, 2, 4]])

[ 2  8 15]


In [32]:
print(a[[0, 1, 2], 1:3])

[[ 2  3]
 [ 7  8]
 [12 13]]


**布尔索引**

可以通过布尔数组对数组进行索引

In [33]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [35]:
print(a[a > 5])

[6 7 8 9]


In [36]:
b = a > 5
print(b)
print(a[b])

[False False False False False  True  True  True  True]
[6 7 8 9]



### 数组迭代 ###

在 NumPy 中，除了 `for` 循环以外，还有另一种方法可以对数组进行迭代：

`apply_along_axis(func1d, axis, arr)` Apply a function to 1-D slices along the given axis.

In [37]:
a = np.arange(1, 26).reshape([5, 5])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [39]:
b = np.apply_along_axis(np.sum, 0, a)
print(b)

[55 60 65 70 75]


In [40]:
b = np.apply_along_axis(np.sum, 1, a)
print(b)

[ 15  40  65  90 115]


In [44]:
def my_func(x):
    return (x[0] + x[-1]) * 0.5


b = np.apply_along_axis(my_func, 0, a)
print(b)

[11. 12. 13. 14. 15.]
