### 数学函数

向量化和广播这两个概念是 numpy 内部实现的基础。有了向量化，编写代码时无需使用显式循环。这些循环实际上不能省略，只不过是在内部实现，被代码中的其他结构代替。向量化的应用使得代码更简洁，可读性更强，也可以说使用了向量化方法的代码看上去更“Pythonic”。

广播（Broadcasting）机制描述了 numpy 如何在算术运算期间处理具有不同形状的数组，让较小的数组在较大的数组上“广播”，以便它们具有兼容的形状。并不是所有的维度都要彼此兼容才符合广播机制的要求，但它们必须满足一定的条件。

若两个数组的各维度兼容，也就是两个数组的每一维等长，或其中一个数组为 一维，那么广播机制就适用。如果这两个条件不满足，numpy就会抛出异常，说两个数组不兼容。

In [6]:
import numpy as np

# 一维数组与二维数组运算

a = np.ones([3, 3])
b = np.arange(1, 4)
print(a.shape, b.shape)
print(a + b)

(3, 3) (3,)
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [9]:
# 一维数组运算

a = np.ones([1, 3])
b = np.arange(1, 7).reshape([6, 1])
print(a.shape, b.shape)
print(a + b)

(1, 3) (6, 1)
[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]]


**算术运算**

- `numpy.add(x1, x2, *args, **kwargs)` 两数组元素相加
- `numpy.subtract(x1, x2, *args, **kwargs)` 两数组元素相减
- `numpy.multiply(x1, x2, *args, **kwargs)` 两数组元素相乘
- `numpy.divide(x1, x2, *args, **kwargs)` 两数组元素相除
- `numpy.floor_divide(x1, x2, *args, **kwargs)` 两数组元素相除并向下取整
- `numpy.power(x1, x2, *args, **kwargs)` 第一个数组为底数，第二个数组为指数乘方

上述方法可以用运算符 `+`, `-`, `*`, `/`, `//`, `**` 表示。其中作用范围为元素级，即两数组中位置相同的元素之间运算。

In [10]:
a = np.ones([1, 3])
b = np.arange(1, 7).reshape([6, 1])
print(a.shape, b.shape)
print(a + b)
print(np.add(a, b))

(1, 3) (6, 1)
[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]]
[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]]


- `numpy.sqrt(x, *args, **kwargs)` 返回 x 中非负元素的平方根
- `numpy.square(x, *args, **kwargs)` 返回 x 中元素的平方

In [12]:
a = np.arange(1, 10)
print(np.sqrt(a))
print(np.square(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[ 1  4  9 16 25 36 49 64 81]


**三角函数**

- `numpy.sin(x, *args, **kwargs)` 
- `numpy.cos(x, *args, **kwargs)` 
- `numpy.tan(x, *args, **kwargs)` 
- `numpy.arcsin(x, *args, **kwargs)` 
- `numpy.arccos(x, *args, **kwargs)`
- `numpy.arctan(x, *args, **kwargs)` 

不解释

**指数和对数**

- `numpy.exp(x, *args, **kwargs)` 计算 e 的 x 次方
- `numpy.log(x, *args, **kwargs)` 计算 x 的自然对数
- `numpy.exp2(x, *args, **kwargs)` 计算 2 的 x 次方
- `numpy.log2(x, *args, **kwargs)` 计算 x 以 2 为底的对数
- `numpy.log10(x, *args, **kwargs)` 计算 x 以 10 为底的对数

In [15]:
a = np.arange(1, 5)
b = np.exp(a)
print(b)
c = np.log(b)
print(c)
print(a == c)

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1. 2. 3. 4.]
[ True  True  True  True]


**数组内操作**

- `numpy.sum(a[, axis=None, dtype=None, out=None, …])` 给定轴元素的和
- `numpy.cumsum(a, axis=None, dtype=None, out=None)` 给定轴元素的累加和
- `numpy.prod(a[, axis=None, dtype=None, out=None, …])` 给定轴元素的积
- `numpy.cumprod(a, axis=None, dtype=None, out=None)` 给定轴元素的累加积

其中 `axis` 参数为空时，返回整个数组的对应和或积

In [21]:
a = np.arange(1, 9).reshape([2, 2, 2])
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.cumsum())
print(a.prod())
print(a.prod(axis=2))
print(a.cumprod(axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
36
[[ 6  8]
 [10 12]]
[ 1  3  6 10 15 21 28 36]
40320
[[ 2 12]
 [30 56]]
[[[ 1  2]
  [ 3  8]]

 [[ 5  6]
  [35 48]]]


**舍入**
- `numpy.around(a, decimals=0, out=None)` 四舍五入到指定小数位
- `numpy.ceil(x, *args, **kwargs)` 向上取整
- `numpy.floor(x, *args, **kwargs)` 向下取整

In [27]:
a = np.random.rand(3, 3) * 10
print(np.around(a, decimals=2))
print(np.ceil(a))
print(np.floor(a))

[[1.59 6.39 4.17]
 [5.35 0.02 5.89]
 [2.07 4.87 4.13]]
[[2. 7. 5.]
 [6. 1. 6.]
 [3. 5. 5.]]
[[1. 6. 4.]
 [5. 0. 5.]
 [2. 4. 4.]]


Note：对于负数，`ceil()` 和 `floor()` 结果与正数不同

In [28]:
a = np.array([-1.7, -1.3])
print(np.around(a))
print(np.ceil(a))
print(np.floor(a))

[-2. -1.]
[-1. -1.]
[-2. -2.]


### 逻辑函数

- `numpy.all(a, axis=None, out=None, keepdims=np._NoValue)` 检测给定数组是否全部元素均为 True
- `numpy.any(a, axis=None, out=None, keepdims=np._NoValue)` 检测给定数组是否有任意元素为 True


In [31]:
a = np.array([0, 1, 2])
b = a.copy()
print(np.all(a == b))
print(np.any(a == b))
b[0] = 1
print(np.all(a == b))
print(np.any(a == b))

True
True
False
True


- `numpy.isnan(x, *args, **kwargs)` 检测数组元素是否为 NaN，返回 `bool` 数组。用于数据清洗

In [32]:
a = np.array([1, 2, np.nan])
print(np.isnan(a))

[False False  True]


**逻辑运算**
- `numpy.logical_not(x, *args, **kwargs)` 取非
- `numpy.logical_and(x1, x2, *args, **kwargs)` 取与
- `numpy.logical_or(x1, x2, *args, **kwargs)` 取或
- `numpy.logical_xor(x1, x2, *args, **kwargs)` 取异或

不解释

- `numpy.greater(x1, x2, *args, **kwargs)` 
- `numpy.greater_equal(x1, x2, *args, **kwargs)` 
- `numpy.equal(x1, x2, *args, **kwargs)` 
- `numpy.not_equal(x1, x2, *args, **kwargs)` 
- `numpy.less(x1, x2, *args, **kwargs)` 
- `numpy.less_equal(x1, x2, *args, **kwargs)` 

可以用对应运算符 `>`, `>=`, `==`, `!=`, `<`, `<=` 运算