**更改数组形状**

- `numpy.ndarray.shape`表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 `ndim` 属性(秩)。
- `numpy.reshape(a, newshape[, order='C'])`在不更改数据的情况下为数组赋予新的形状。
- `numpy.ndarray.reshape(newshape[, order='C'])`也可以改变数组的形状

Note:
- order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。(简记)
- order：{'C / F，'A，K}，可选使用此索引顺序读取a的元素。'C'意味着以行大的C风格顺序对元素进行索引，最后一个轴索引会更改F表示以列大的Fortran样式顺序索引元素，其中第一个索引变化最快，最后一个索引变化最快。请注意，'C'和'F'选项不考虑基础数组的内存布局，仅引用轴索引的顺序.A'表示如果a为Fortran，则以类似Fortran的索引顺序读取元素在内存中连续，否则类似C的顺序。“ K”表示按照步序在内存中的顺序读取元素，但步幅为负时反转数据除外。默认情况下，使用Cindex顺序。

In [1]:
import numpy as np
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
a = a.reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(a.shape)
a.shape = [9]
print(a)

(1, 9)
[1 2 3 4 5 6 7 8 9]


In [8]:
a = np.reshape(a, [3, 3])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- `numpy.ndarray.flat` 将数组转换为一维的迭代器，可以用for访问数组每一个元素。
- `numpy.ndarray.flatten([order='C'])` 将数组的拷贝转换为一维数组，并返回。

In [9]:
a = np.arange(1, 10).reshape([3, 3])
x = a.flat
print(x)
y = a.flatten()
print(y)

[1 2 3 4 5 6 7 8 9]


In [10]:
for i in x:
    print(i)

1
2
3
4
5
6
7
8
9


**数组转置**
- `numpy.transpose(a, axes=None)` 重新排列数组的维度
- `numpy.ndarray.T` 与 `self.transpose()` 相同，但是当数组维度 < 2时返回其本身

In [11]:
a = np.arange(1, 26).reshape([5, 5])
print(a.T)
print(np.transpose(a))

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


**更改维度**

当创建一个数组之后，还可以给它增加一个维度，这在矩阵计算中经常会用到。

`numpy.newaxis = None` `None`的别名，对索引数组很有用。

In [13]:
x = np.array([1, 2, 9, 4, 5, 6, 7, 8])
print(x.shape)
print(x)

(8,)
[1 2 9 4 5 6 7 8]


In [14]:
y = x[np.newaxis, :]
print(y.shape)
print(y)

(1, 8)
[[1 2 9 4 5 6 7 8]]


In [15]:
y = x[:, np.newaxis]
print(y.shape)
print(y)

(8, 1)
[[1]
 [2]
 [9]
 [4]
 [5]
 [6]
 [7]
 [8]]


**数组组合**

如果要将两份数据组合到一起，就需要拼接操作。

`numpy.concatenate((a1, a2, ...), axis=0, out=None)` 将两个数组按存在的轴拼接

In [16]:
x = np.array([1, 2, 3])
y = np.array([7, 8, 9])
z = np.concatenate([x, y])
print(z)

[1 2 3 7 8 9]


In [17]:
z = np.concatenate([x, y], axis=0)
print(z)

[1 2 3 7 8 9]


In [18]:
x = np.array([1, 2, 3]).reshape(1, 3)
y = np.array([7, 8, 9]).reshape(1, 3)
z = np.concatenate([x, y])
print(z)

[[1 2 3]
 [7 8 9]]


In [19]:
z = np.concatenate([x, y], axis=0)
print(z)

[[1 2 3]
 [7 8 9]]


In [20]:
z = np.concatenate([x, y], axis=1)
print(z)

[[1 2 3 7 8 9]]


In [21]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.concatenate([x, y])
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
z = np.concatenate([x, y], axis=0)
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
z = np.concatenate([x, y], axis=1)
print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


`numpy.stack(arrays, axis=0, out=None)` 将两个数组沿新的轴拼接

In [24]:
x = np.array([1, 2, 3])
y = np.array([7, 8, 9])
z = np.stack([x, y])
print(z.shape)
print(z)

(2, 3)
[[1 2 3]
 [7 8 9]]


**数组拆分**

`numpy.split(ary, indices_or_sections, axis=0)` 将数组拆分为多个子数组

In [25]:
x = np.array([[11, 12, 13, 14],
              [16, 17, 18, 19],
              [21, 22, 23, 24]])
y = np.split(x, [1, 3])
print(y)

[array([[11, 12, 13, 14]]), array([[16, 17, 18, 19],
       [21, 22, 23, 24]]), array([], shape=(0, 4), dtype=int64)]
