### 排序，搜索和计数

**排序**

- `numpy.sort(a[, axis=-1, kind='quicksort', order=None])` 返回数组排序后的复制。
    - axis：排序沿数组的（轴）方向，0表示按行，1表示按列，None表示展开来排序，默认为-1，表示沿最后的轴排序。
    - kind：排序的算法，提供了快排'quicksort'、混排'mergesort'、堆排'heapsort'， 默认为‘quicksort'。
    - order：排序的字段名，可指定字段排序，默认为None。



In [8]:
import numpy as np
a = np.random.rand(5, 5) * 10
a = np.around(a, 2)
print(a)

[[9.93 4.23 7.67 7.86 6.64]
 [5.1  5.79 4.75 6.34 5.46]
 [2.16 6.14 4.77 3.33 4.43]
 [7.73 0.72 5.19 3.52 7.06]
 [1.86 1.45 2.52 9.47 9.55]]


In [10]:
print(np.sort(a))
print(np.sort(a, axis=0))
print(np.sort(a, axis=None))

[[4.23 6.64 7.67 7.86 9.93]
 [4.75 5.1  5.46 5.79 6.34]
 [2.16 3.33 4.43 4.77 6.14]
 [0.72 3.52 5.19 7.06 7.73]
 [1.45 1.86 2.52 9.47 9.55]]
[[1.86 0.72 2.52 3.33 4.43]
 [2.16 1.45 4.75 3.52 5.46]
 [5.1  4.23 4.77 6.34 6.64]
 [7.73 5.79 5.19 7.86 7.06]
 [9.93 6.14 7.67 9.47 9.55]]
[0.72 1.45 1.86 2.16 2.52 3.33 3.52 4.23 4.43 4.75 4.77 5.1  5.19 5.46
 5.79 6.14 6.34 6.64 7.06 7.67 7.73 7.86 9.47 9.55 9.93]


- `numpy.argsort(a[, axis=-1, kind='quicksort', order=None])` 返回排序后数组的索引

In [12]:
print(a)
print(np.argsort(a))

[[9.93 4.23 7.67 7.86 6.64]
 [5.1  5.79 4.75 6.34 5.46]
 [2.16 6.14 4.77 3.33 4.43]
 [7.73 0.72 5.19 3.52 7.06]
 [1.86 1.45 2.52 9.47 9.55]]
[[1 4 2 3 0]
 [2 0 4 1 3]
 [0 3 4 2 1]
 [1 3 2 4 0]
 [1 0 2 3 4]]


In [13]:
print(np.argsort(a, axis=0))
print(np.argsort(a, axis=None))

[[4 3 4 2 2]
 [2 4 1 3 1]
 [1 0 2 1 0]
 [3 1 3 0 3]
 [0 2 0 4 4]]
[16 21 20 10 22 13 18  1 14  7 12  5 17  9  6 11  8  4 19  2 15  3 23 24
  0]


- `numpy.lexsort(keys[, axis=-1])` 使用键序列执行间接稳定排序。

给定多个可以在电子表格中解释为列的排序键，lexsort返回一个整数索引数组，该数组描述了按多个列排序的顺序。序列中的最后一个键用于主排序顺序，倒数第二个键用于辅助排序顺序，依此类推。keys参数必须是可以转换为相同形状的数组的对象序列。如果为keys参数提供了2D数组，则将其行解释为排序键，并根据最后一行，倒数第二行等进行排序。

In [16]:
a = np.random.rand(5, 5) * 10
a = np.around(a, 2)
print(a)
i = np.lexsort([a[:, 0]])
print(i)
b = a[i]
print(b)

[[5.45 5.4  2.93 1.52 9.96]
 [9.25 7.26 8.82 0.41 8.3 ]
 [1.88 0.84 2.57 1.35 4.12]
 [4.78 8.79 1.51 0.86 5.11]
 [4.35 4.97 5.13 5.77 2.07]]
[2 4 3 0 1]
[[1.88 0.84 2.57 1.35 4.12]
 [4.35 4.97 5.13 5.77 2.07]
 [4.78 8.79 1.51 0.86 5.11]
 [5.45 5.4  2.93 1.52 9.96]
 [9.25 7.26 8.82 0.41 8.3 ]]


- `numpy.partition(a, kth, axis=-1, kind='introselect', order=None)` 返回分割后的数组

创建数组的复制使得第k大的元素在第k个位置，小于其的元素位于其左侧，大于等于其的元素位于其右侧。

In [17]:
x = np.random.randint(1, 30, [8, 3])
print(x)

y = np.sort(x, axis=0)
print(y)

z = np.partition(x, kth=2, axis=0)
print(z)

[[26 18 28]
 [15 10 22]
 [22 11 25]
 [ 8  4 22]
 [24 15 22]
 [19 16 28]
 [15 23 10]
 [27 29 20]]
[[ 8  4 10]
 [15 10 20]
 [15 11 22]
 [19 15 22]
 [22 16 22]
 [24 18 25]
 [26 23 28]
 [27 29 28]]
[[ 8  4 10]
 [15 10 20]
 [15 11 22]
 [26 18 25]
 [24 15 22]
 [19 16 28]
 [22 23 28]
 [27 29 22]]


**搜索**
- `numpy.argmax(a[, axis=None, out=None])` 返回数组给定轴最大值的索引
- `numpy.argmin(a[, axis=None, out=None])` 返回数组给定轴最小值的索引

In [18]:
a = np.random.randint(0, 10, 10)
print(a)

[4 7 6 5 6 7 8 0 3 1]


In [19]:
print(a.argmax())
print(a.argmin())

6
7


- `numpy.nonzero(a)` 返回数组中非零元素的下标

返回一个 tuple，其长度等于数组维度。tuple 中每个元素为一个数组，长度等于原数组中非零元素的个数。tuple 中第 i 个数组的第 j 项表示原数组中第 j 个非零元素在第 i 维的下标。

In [27]:
a = np.array([0, 3, 2, 0])
b = a.nonzero()
print(b)

(array([1, 2]),)


In [28]:
a = np.array([[0, 1, 2], [1, 0, 2], [1, 2, 0]])
b = a.nonzero()
print(b)

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 2, 0, 1]))


- `numpy.where(condition, [x=None, y=None])`  满足条件 `condition` 则返回 `x`，否则返回 `y`

In [29]:
a = np.arange(1, 10)
b = np.where(a > 5, a, 0)
print(b)

[0 0 0 0 0 6 7 8 9]


- `numpy.searchsorted(a, v[, side='left', sorter=None])` 找到使插入元素后，数组依然有序的下标
    - a：一维输入数组。当`sorter`参数为`None`的时候，`a`必须为升序数组；否则，`sorter`不能为空，存放`a`中元素的`index`，用于反映`a`数组的升序排列方式。
    - v：插入`a`数组的值，可以为单个元素，`list`或者`ndarray`。
    - side：查询方向，当为`left`时，将返回第一个符合条件的元素下标；当为`right`时，将返回最后一个符合条件的元素下标。
    - sorter：一维数组存放`a`数组元素的 index，index 对应元素为升序。

In [31]:
a = np.arange(1, 10)
print(a)
print(np.searchsorted(a, 1))
print(np.searchsorted(a, 1, side='right'))
print(np.searchsorted(a, 11))

[1 2 3 4 5 6 7 8 9]
0
1
9


**计数**
- `numpy.count_nonzero(a, axis=None)` 返回数组中非0元素的个数

In [33]:
a = np.array([0, 1, 2, 3, 0])
print(np.count_nonzero(a))

3
